spring:
    application:
        name:Heroes

    datasource:
        driver-class-name:org.postgresql.Driver
        username:postgres
        password:root
        url:jdbc:postgresql://postgres-server/linuxone

    jpa:
        database-platform:org.hibernate.dialect.PostgreSQLDialect
